"""add weekly plans

Revision ID: 27bcb0eaaca9
Revises: 0001
Create Date: 2026-07-17 09:56:43.958234
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '27bcb0eaaca9'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('mesocycle_type', sa.String(length=16), nullable=False),
    sa.Column('week_type', sa.String(length=32), nullable=False),
    sa.Column('coach_rationale', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('workouts', sa.Column('weekly_plan_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'workouts', 'weekly_plans', ['weekly_plan_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workouts', type_='foreignkey')
    op.drop_column('workouts', 'weekly_plan_id')
    op.drop_table('weekly_plans')
    # ### end Alembic commands ###
